### ISSUE TITLE
Sharing with QR isnt working

### ISSUE THREAD

**Issue by Afnyc252** [cachapa/tudo#41] opened 2024-08-22 09:29 UTC
I really like the app. Please let me know if you need any further information

I tried sharing a list with another Tudo user with the QR code. The user started tried to add from the clean slate screen. The screen got stuck in "joining list". 

Previously (about two weeks ago) this problem existed but after closing and reopening the app (of the one trying to join), it turned out that the list was added anyway. So I tried the same approach again, but it didnt work this time.

Im new to github and coding, if my feedback is not useable for some reason please let me know.

**Comment by cachapa** [comment] 2024-08-22 09:58
Duplicate of #40

**Closed by cachapa** 2024-08-22 09:58 UTC

**Comment by cachapa** [comment] 2024-08-22 10:06
Thanks a lot for the reports and for the feedback. This is the unfortunate result of me being on vacation and not having access to the tools necessary to access the server when things go wrong.

**Comment by Afnyc252** [comment] 2024-08-22 11:48
Glad to help :)

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: Daniel Cachapa ***@***.***>
Verzonden: Thursday, August 22, 2024 12:06:30 PM
Aan: cachapa/tudo ***@***.***>
CC: Afnyc252 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [cachapa/tudo] Sharing with QR isnt working (Issue #41)


Thanks a lot for the reports and for the feedback. This is the unfortunate result of me being on vacation and not having access to the tools necessary to access the server when things go wrong.
